import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Gantari:wght@200;400;500&family=Tillana:wght@700&display=swap"
          rel="stylesheet"
        />
        <title>Refaleikarnir</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
